openapi: 3.0.3
info:
  title: REST VTEX
  version: 2.0.0
  description: Documentação da API responsável pela integração de operações de crédito e clientes entre o ERP TOTVS Protheus e o E-Commerce VTEX.
  # summary: Integração de operações de crédito e clientes
  contact:
    name: Suporte TI
    email: suporteti@comercialqueiroz.com.br
  x-logo:
    url: 'https://github.com/crysataide/rest-vtex/blob/main/rest-vtex-logo.png'
    # backgroundColor: '#FFFFFF'
    altText: 'REST VTEX logo'
servers:
  - url: https://wkrtswcddl.execute-api.us-east-2.amazonaws.com/vtex/rest
    description: Produção
  - url: https://htztymyfp1.execute-api.us-east-2.amazonaws.com/hom/rest
    description: Homologação
paths:
  /api/oauth2/v1/token:
    post:
      tags:
        - Auth
      summary: Autenticação
      operationId: auth
      description: "A autenticação deve ser feita e o token gerado deve estar presente em todas as requisições."
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RequestToken'
      responses:
        '200':
          description: Token gerado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          description: Erro nos parâmetros
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorToken'
  /vtex/creditLimit/{document}:
    get:
      tags:
        - Cliente
      parameters:
        - in: path
          name: document
          required: true
          schema:
            type: string
            example: "00000000000"
          allowReserved: true
      summary: Limite de crédito
      operationId: creditLimit
      description: Consulta informações de crédito do cliente com base no CPF/CNPJ
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditLimit'
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  message: "Cliente não encontrado"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Bad Body:
                  value:
                    message: "Body não informado"
                Bad Document:
                  value:
                    message: "Documento inválido"
  /vtex/customer:
    patch:
      tags:
        - Cliente
      summary: Sincroniza cliente
      description: Cria ou atualiza o cadastro de um cliente pessoa jurídica no ERP. Quando `requestedAnalysis` for igual a `true`, também será solicitada uma análise de crédito para o cliente.
      operationId: syncCustomer
      requestBody:
        required: true
        description: Dados cadastrais e comerciais do cliente pessoa jurídica.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Cliente sincronizado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '400':
          description: Requisição inválida ou dados insuficientes para sincronização.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                bodyNaoInformado:
                  summary: Corpo da requisição não informado
                  value:
                    message: "Body não informado"
                dadosDoClienteInvalidos:
                  summary: Falha na sincronização cadastral
                  value:
                    message: "Erro na sincronização dos dados do cliente"
                analiseDeCreditoInvalida:
                  summary: Falha na solicitação da análise de crédito
                  value:
                    message: "Erro na sincronização da análise de crédito"
  /vtex/creditReserve:
    post:
      tags:
        - Reserva
      summary: Reserva de crédito
      description: Realiza a reserva de crédito do valor informado
      operationId: createCreditReserve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditReserveRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditReserve'
              examples:
                Reserva Criada:
                  value:
                    cardId: '04791601'
                    id: '000001'
                    refUrl: /rest
                    status: 'pending'
                Reserva Já Existente:
                  value:
                    message: '  Pedido já possui uma reserva'
                    id: '000001'
                    status: 'pending|authorized|confirmed|canceled'
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: 'Cliente não encontrado'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Body:
                  value:
                    message: 'Body não informado'
                Cliente:
                  value:
                    message: 'ID do cliente inválido'
                Erro Reserva:
                  value:
                    message: 'Ocorreu um erro na geração da reserva'
                Reserva Zerada:
                  value:
                    message: 'Valor para reserva zerado'
                Saldo Insuficiente:
                  value:
                    message: 'Saldo insuficiente para realizar a reserva'
                    balance: 0
                    value: 5000
  /vtex/authorization/{customerId}/reserve/{id}:
    get:
      tags:
        - Reserva
      summary: Consulta autorização
      description: Consulta status da transação
      operationId: transactionAuthorization
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
            example: '04791601'
          allowReserved: true
        - in: path
          name: id
          required: true
          schema:
            type: string
            example: '000131'
          allowReserved: true
      responses:
        '200':
          description: Reserva Rejeitada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserve'
              example:
                  message: "Transação rejeitada"
                  status: "rejected"
        '202':
          description: Reserva Autorizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserve'
              examples:
                Success:
                  value:
                    oid: '000001'
                    value: 5000
                    date: '1900-07-07T12:00:00Z'
                    status: 'authorized'
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Cliente:
                  value:
                    message: Cliente não encontrado
                Reserva:
                  value:
                    message: Reserva não encontrada
                Pedido:
                  value:
                    message: Pedido nao encontrado
        '206':
          description: Reserva Pendente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserve'
              examples:
                Success:
                  value:
                    oid: null
                    value: 0
                    date: null
                    status: 'pending'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Body:
                  value:
                    message: Body não informado
                Id inválido:
                  value:
                    message: ID da transação inválida
                Id Cliente inválido:
                  value:
                    message: ID do cliente inválido
                Reserva:
                  value:
                    message: Reserva nao atualizada
  /vtex/cancellation/{customerId}/reserve/{id}:
    post:
      tags:
        - Reserva
      summary: Cancela transação
      description: Realiza o cancelamento da transação e estorna o valor.
      operationId: cancelTransaction
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
            example: '04791601'
          allowReserved: true
        - in: path
          name: id
          required: true
          schema:
            type: string
            example: '86000131'
          allowReserved: true
      responses:
        '200':
          description: Reserva Cancelada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserve'
              examples:
                Success:
                  value:
                    oid: '000001'
                    value: 5000
                    date: '1900-07-07T12:00:00Z'
                    status: 'canceled'
        '204':
          description: No Content
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/Error'
              examples:
                Cliente:
                  value:
                    message: Cliente não encontrado.
                Reserva:
                  value:
                    message: Reserva não encontrada.
                Transação:
                  value:
                    message: Transação não encontrada.
        '400':
          description: Bad Request
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/Error'
              examples:
                Body:
                  value:
                    message: Body não informado.
                Id Inválido:
                  value:
                    message: ID da transação inválida.
                Id Cliente:
                  value:
                    message: ID do cliente inválido.
  /vtex/confirmation/{customerId}/reserve/{id}:
    post:
      tags: 
        - Reserva
      summary: Confirma transação
      description: Realiza a confirmação da transação
      operationId: confirmTransaction
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
            example: '04791601'
          allowReserved: true
        - in: path
          name: id
          required: true
          schema:
            type: string
            example: '86000131'
          allowReserved: true
      responses:
        '202':
          description: Reserva Autorizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserve'
              examples:
                Success:
                  value:
                    oid: '000001'
                    value: 5000
                    date: '1900-07-07T12:00:00Z'
                    status: 'confirmed'
        '204':
          description: No Content
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Cliente:
                  value:
                    message: Cliente não encontrado
                Reserva:
                  value:
                    message: Reserva não encontrada
                Transação:
                  value:
                    message: Transação não encontrada
        '400':
          description: Bad Request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Body:
                  value:
                    message: Body não informado
                Id Inválido:
                  value:
                    message: ID da transação inválida
                Id Cliente:
                  value:
                    message: ID do cliente inválido
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: Insira sua chave de API de integração.
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Insira o token de integração.
  schemas:
    CreditReserveRequest:
      type: object
      required:
        - customerId
        - paymentCondition
        - orderId
        - value
        - requestId
      properties:
        customerId:
          type: string
          description: "Identificador único do cliente"
          example: "04791601"
        paymentCondition:
          type: string
          minLength: 3
          maxLength: 3
          description: "Identificador único da condição de pagamento escolhida"
          example: "011"
        orderId:
          type: string
          description: "Identificador do pedido"
          example: '1643890500037-01'
        value:
          type: number
          format: double
          description: "Valor da reserva em centavos"
          example: 50000
        requestId:
          type: string
          description: "Identificador da requisição"
          example: "50E828C435434B1D8A7CA8AB93AFF39F"
    RequestToken:
      type: object
      required:
        - username
        - password
        - grant_type
      properties:
        username:
          type: string
          example: 'admin'
        password:
          type: string
          example: '123456'
        grant_type:
          type: string
          example: 'password'
    Token:
      type: object
      properties:
        access_token:
          type: string
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
        refresh_token:
          type: string
          example: 'DFMoDHc5QnRzijJ2pQCdiIjX.JWkZVF8AFC1...'
        scope:
          type: string
          example: 'default'
        token_type:
          type: string
          example: 'Bearer'
        expires_in:
          type: integer
          example: 3600
        hasMFA:
          type: boolean
          example: false
    CreditLimit:
      type: object
      required:
        - customerId
        - availableBalance
        - creditLimit
      properties:
        customerId:
          type: string
          description: Identificador único do cliente
          example: '04791601'
        availableBalance:
          type: number
          description: "Saldo disponível atual para utilização"
          example: 1000000
        creditLimit:
          type: number
          description: "Valor total do limite originalmente concedido"
          example: 1000000
        paymentConditions:
          type: array
          description: "Informações das condições de pagamento do cliente"
          items:
            - $ref: "#/components/schemas/CustomerConditions1"
            - $ref: "#/components/schemas/CustomerConditions2"
    Customer:
      type: object
      required:
        - customerId
        - corporateName
        - tradeName
        - email
        - document
        - stateRegistration
        - homePhone
        - requestedAnalysis
        - address
      properties:
        customerId:
          type: string
          format: uuid
          description: Identificador único do cliente na VTEX.
          example: "12f26a2d-e9eb-4e76-8ec3-400444be7bc5"
        corporateName:
          type: string
          description: Razão social do cliente.
          example: COMUNICACAO LTDA
        tradeName:
          type: string
          description: Nome fantasia do cliente.
          example: COMUNI MAIS
        email:
          type: string
          description: Endereço de e-mail corporativo do cliente.
          example: comunimais@corporate.com
        document:
          type: string
          description: CNPJ do cliente, com ou sem formatação.
          example: "99.999.999/9999-99"
        stateRegistration:
          type: string
          description: Inscrição estadual do cliente
          example: 99.999.999-9
        homePhone:
          type: string
          description: Número de telefone principal do cliente, incluindo o DDD.
          example: "11999999999"
        requestedAnalysis:
          type: boolean
          description: Indica se deve ser solicitada uma análise de crédito após a sincronização cadastral.
          example: true
        address:
          $ref: "#/components/schemas/CustomerAddress"
    CustomerAddress:
      type: object
      description: "Informações de endereço do cliente"
      required:
        - postalCode
        - state
        - city
        - neighborhood
        - street
        - number
      properties:
        postalCode:
          type: string
          description: CEP do endereço, com ou sem formatação.
          example: "03310-000"
        state:
          type: string
          minLength: 2
          maxLength: 2
          description: Sigla da unidade federativa.
          example: SP
        city:
          type: string
          description: Município do endereço.
          example: "São Paulo"
        neighborhood:
          type: string
          description: Bairro do endereço.
          example: "Tatuapé"
        street:
          type: string
          description: Logradouro do endereço.
          example: "R. do Tatuapé"
        number:
          type: string
          description: Número do imóvel.
          example: "999"
        complement:
          type: string
          description: "Complemento do endereço"
          example: "Sala 10"
        reference:
          type: string
          description: "Ponto de referência do endereço"
          example: "Próximo ao shopping"
    CustomerConditions1:
      type: object
      properties:
        id:
          type: string
          description: Identificador único da condição de pagamento
          example: "010"
        caption:
          type: string
          description: "Texto exibido ao consumidor no checkout"
          example: Crédito Queiroz 07 Dias
        amount:
          type: number
          description: Percentual de acréscimo que a condição de pagamento aplica
          example: 0
        installment:
          type: integer
          description: Quantidade de parcelas que a condição de pagamento aplica
          example: 1
        active:
          type: boolean
          description: Indica se a condição está disponível
          example: true
    CustomerConditions2:
      type: object
      properties:
        id:
          type: string
          description: Identificador único da condição de pagamento
          example: "011"
        caption:
          type: string
          description: "Texto exibido ao consumidor no checkout"
          example: Crédito Queiroz 07/14 Dias
        amount:
          type: number
          description: Percentual de acréscimo que a condição de pagamento aplica
          example: 0.70
        installment:
          type: integer
          description: Quantidade de parcelas que a condição de pagamento aplica
          example: 2
        active:
          type: boolean
          description: Indica se a condição está disponível
          example: true
    CustomerResponse:
      type: object
      required:
        - id
        - balance
        - totalBalance
      properties:
        id:
          type: string
          description: Código do cliente gerado ou localizado no ERP.
          example: '00000101'
        balance:
          type: integer
          format: int64
          description: Crédito disponível para utilização, expresso em centavos.
          example: 1000000
        totalBalance:
          type: integer
          format: int64
          description: Limite total de crédito aprovado para o cliente, expresso em centavos.
          example: 1000000
    CreditReserve:
      type: object
      properties:
        id:
          type: string
          description: "ID único da reserva."
          example: '000001'
        cardId:
          type: string
          description: "ID único do cliente."
          example: '04791601'
        refUrl:
          type: string
          description: "URL de referência da transação."
          example: "/rest/vtex/creditReserve"
        status:
          type: string
          description: "Status da transação"
          example: "peding"
        message:
          type: string
          example: "string"
    Reserve:
      type: object
      properties:
        oid:
          type: string
          nullable: true
          description: "ID único da reserva."
          example: '000001'
        value:
          type: number
          description: "Valor em centávos."
          example: 5000
        date:
          type: string
          nullable: true
          description: "Data/hora (ISO 8601)."
          example: '1900-07-07T12:00:00Z'
        status:
          type: string
          description: "Status da transação."
          example: "pending"
          enum:
            - pending
            - authorized
            - confirmed
            - canceled
            - rejected
        message:
          type: string
          example: "string"
    Error:
      type: object
      properties:
        message:
          type: string
          example: Documento inválido
        balance:
          type: integer
          example: 5000
        value:
          type: integer
          example: 5000
    ErrorToken:
      type: object
      properties:
        code:
          type: integer
          example: 401
        message:
          type: string
          example: "string"
        detailedMessage:
          type: string
          example: "string"
security:
  - bearerAuth: []
    ApiKeyAuth: []
tags:
  - name: Auth
    description: Operações de autenticação e geração de token
  - name: Cliente
    description: Consultas relacionadas ao cliente e limite de crédito
  - name: Reserva
    description: Operações de reserva, autorização, confirmação e cancelamento